version: 1.0.{build}
image: Visual Studio 2015

clone_script:
- git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- git checkout -qf %APPVEYOR_REPO_COMMIT%
- del C:\Tools\WebDriver\geckodriver.exe
- C:/Python37-x64/Scripts/pip.exe install selenium
- C:/Python37-x64/python.exe seleniumtest.py
- C:/msys64/usr/bin/wget.exe -nv https://download.microsoft.com/download/B/C/4/BC4FA89D-4F7B-4022-A4C1-2B3B6E08D8BE/AppBuilderSetup_VS2012_v50806.zip
- REM C:/msys64/usr/bin/wget.exe -nv https://github.com/datadiode/supplements/raw/main/Compact2013_SDK_GSeries.msi
- C:/msys64/usr/bin/wget.exe -nv https://github.com/embedded101/Compact2013.BSP/raw/master/sdk/Compact2013_SDK_86Duino_80B.zip
- 7z.exe x -oAppBuilderSetup AppBuilderSetup_VS2012_v50806.zip
- 7z.exe x Compact2013_SDK_86Duino_80B.zip
- 7z.exe x toradex_ce8_sdk_2.3_bis.zip
- AppBuilderSetup\VSEmbedded_AppBuilder.exe /Quiet /NoRestart /Log log.txt & exit 0
- type log.txt
- REM msiexec /i Compact2013_SDK_GSeries.msi /quiet /norestart /log msilog.txt & exit 0
- msiexec /i Compact2013_SDK_86Duino_80B.msi /quiet /norestart /log msilog.txt & exit 0
- type msilog.txt
- msiexec /i Toradex_CE8_SDK_2_3_bis.msi /quiet /norestart /log msilog.txt & exit 0
- type msilog.txt
- REM wmic product get name

build_script:
- dir
